# References {.unnumbered #sec-references}

Beven, K., 1984. Infiltration into a Class of Vertically Non-Uniform Soils. Hydrological Sciences Journal 29 (4), 425-434. [doi:10.1080/02626668409490960](https://doi.org/10.1080/02626668409490960).

Beven, K., Lamb, R., Quinn, P., Romanowicz, R., Freer, J., 1995. TOPMODEL. In: Singh, V.P. (Ed.), Computer Models of Watershed Hydrology. Water Resources Publications, pp. 627-668.

Beven, K., Binley, A., 2014. GLUE - 20 Years On. *Hydrological Processes* 28 (24), 5897-5918. [https://doi.org/10.1002/hyp.10082](https://doi.org/10.1002/hyp.10082)

Buytaert, W., 2009. TOPMODEL. <https://source.ggy.bris.ac.uk/wiki/Topmodel>, accessed on November 9, 2015.

Cho, H., 2000. GIS Hydrological Modeling System by Using Programming Interface of GRASS. Master’s Thesis, Department of Civil Engineering, Kyungpook National University, South Korea.

Cho, H., Kim, D., Olivera, F., Guikema, S. D., 2011. Enhanced Speciation in Particle Swarm Optimization for Multi-Modal Problems. European Journal of Operational Research 213 (1), 15-23. [doi:10.1016/j.ejor.2011.02.026](https://doi.org/10.1016/j.ejor.2011.02.026).

Cho, H., 2020. A Recursive Algorithm for Calculating the Longest Flow Path and Its Iterative Implementation. Environmental Modelling & Software 131, 104774. [doi:10.1016/j.envsoft.2020.104774](https://doi.org/10.1016/j.envsoft.2020.104774).

Cho, H., Park, J., Kim, D., 2019. Evaluation of Four GLUE Likelihood Measures and Behavior of Large Parameter Samples in ISPSO-GLUE for TOPMODEL. Water 11 (3), 447. [doi:10.3390/w11030447](https://doi.org/10.3390/w11030447).

Conrad, O., 2003. SAGA-GIS Module Library Documentation (v2.1.3) Module TOPMODEL. <http://www.saga-gis.org/saga_module_doc/2.1.3/sim_hydrology_2.html>, accessed on November 9, 2015.

Li, X., 2004. Adaptively Choosing Neighbourhood Bests Using Species in a Particle Swarm Optimizer for Multimodal Function Optimization. Lecture Notes in Computer Science 3102, 105-166. [doi:10.1007/978-3-540-24854-5_10](https://doi.org/10.1007/978-3-540-24854-5_10).

Neteler, M., Bowman, M. H., Landa, M., Metz, M., 2012. GRASS GIS: A Multi-Purpose Open Source GIS. Environmental Modelling & Software 31, 124-130. [doi:10.1016/j.envsoft.2011.11.014](https://doi.org/10.1016/j.envsoft.2011.11.014).

## Technical References {.unnumbered #sec-technical-references}

### `read_write_rtopmodel.R`

- **`write_rtopmodel_params()`**: Updates an existing `r.topmodel` parameters file. NULL parameters are not updated.

  - file="params.txt"
  - qs0=NULL
  - lnTe=NULL
  - m=NULL
  - Sr0=NULL
  - Srmax=NULL
  - td=NULL
  - vch=NULL
  - vr=NULL
  - infex=NULL
  - K0=NULL
  - psi=NULL
  - dtheta=NULL

- **`write_rtopmodel_x()`**: Updates an existing `r.topmodel` parameters file using parameter values normalized to [0, 1].

  - file="params.txt"
  - x: All parameter values need to be passed in the order of parameter arguments for `write_rtopmodel_params()`.

- **`read_rtopmodel_params`**: Reads parameter values from an existing `r.topmodel` parameters file and returns them as a list.

  - file="params.txt"

- **`read_rtopmodel_params_from_lnes()`**: Reads parameter values from lines read by `readLine()`.
  
  - lines

- **`read_rtopmodel_output()`**: Reads a variable from an `r.topmodel` output file.

  - file="output.txt"
  - name="Qt": Either "Qt", "qt", "qo", "qs", "qv", "S_mean", "f", or "fex".

---

### `run_rtopmodel.R`

- **`par.name`**: Parameter names.
- **`par.dim`**: Number of parameters.
- **`par.min`**: Lower limits of parameter values.
- **`par.max`**: Upper limits of parameter values.

- **`run_rtopmodel_x()`**: Runs `r.topmodel` with parameter values normalized to [0, 1].

  - x: All parameter values need to be passed in the order of parameter arguments for `write_rtopmodel_params()`.
  - path=list(params="params.txt", topidxstats="topidxstats.txt", input="input.txt", output="output.txt", sim="sim")
  - append=FALSE: If TRUE, `x` will be appended to `sim/x.txt` and unnormalized parameter values to `sim/parval.txt`.

- **`run_rtopmodel()`**: Runs `r.topmodel` with the current parameters file.

  - path=list(params="params.txt", topidxstats="topidxstats.txt", input="input.txt", output="output.txt", sim="sim")