# Requirements {.unnumbered}

## Software requirements

- Operating systems: [Linux](https://www.kernel.org/), [macOS](https://www.apple.com/macos/), [Windows](https://www.microsoft.com/windows/)
- [Git](https://git-scm.com/)
- [GRASS GIS](https://grass.osgeo.org/)

  - [r.accumulate](https://grass.osgeo.org/grass-stable/manuals/addons/r.accumulate.html) to be installed using [g.extension](https://grass.osgeo.org/grass-stable/manuals/g.extension.html)

- [Python 3](https://www.python.org/) installed with GRASS GIS

  - [ProjPicker](https://projpicker.readthedocs.io/)

- [R](https://www.r-project.org/)

  - [fOptions package](https://cran.r-project.org/web/packages/fOptions/index.html)
  - [plotrix package](https://cran.r-project.org/web/packages/plotrix/index.html)

- [Workshop Python/R scripts](https://github.com/HuidaeCho/nsf-pose-2025-r.topmodel-workshop/tree/master/scripts)

## GitHub repository for the workshop

Clone the workshop repository from <https://github.com/HuidaeCho/nsf-pose-2025-r.topmodel-workshop>.

```bash
git clone https://github.com/HuidaeCho/nsf-pose-2025-r.topmodel-workshop.git
```

We will run this workshop from `nsf-pose-2025-r.topmodel-workshop/run`.

```bash
cd nsf-pose-2025-r.topmodel-workshop
mkdir run
cd run
```

## Data requirements

### r.topmodel data

[r.topmodel](https://grass.osgeo.org/grass-stable/manuals/r.topmodel.html) requires the following inputs:

- rainfall time series
- evapotranspiration time series
- a topographic index statistics file generated by preprocessing (`r.topmodel -p`)

### r.topidx data

[r.topidx](https://grass.osgeo.org/grass-stable/manuals/r.topidx.html) requires an elevation raster map.

### Data sources

#### Digital elevation models

The following digital elevation model (DEM) products cover most of the world:

- [Shuttle Radar Topography Mission (SRTM)](https://www2.jpl.nasa.gov/srtm/)
- [Advanced Spaceborne Thermal Emission and Reflection Radiometer (ASTER) Global Digital Elevation Model](https://asterweb.jpl.nasa.gov/gdem.asp)
- [Advanced Land Observing Satellite (ALOS) World 3D - 30m](https://www.eorc.jaxa.jp/ALOS/en/aw3d30/)

All these products are available free of charge in 1°x1° tiles at a 1-arcsecond (approximately 30-m) resolution.

ASTER and SRTM data can be downloaded from [EarthExplorer](https://earthexplorer.usgs.gov/).

#### Weather forcing data

The National Centers for Environmental Information ([NCEI](https://www.ncei.noaa.gov/)) provides an application programming interface (API) for downloading weather data from [the Climate Data Online (CDO) web services](https://www.ncdc.noaa.gov/cdo-web/webservices/v2).